server:
  port: 9090

spring:
  application:
    name: authorization-api
  datasource:
    url: jdbc:h2:mem:authorization-db
    driver-class-name: org.h2.Driver
    username: authorization-username
    password: authorization-password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

authorization-api:
  redis:
    host: localhost
    port: 6379
