server:
  port: 9090

spring:
  application:
    name: authorization-api
  data:
    mongodb:
      host: localhost
      port: 27017
      database: authorization-db

authorization-api:
  redis:
    host: localhost
    port: 6379
  admin:
    id: 1234
    username: admin
    password: $2a$12$KwhGOUehFkFW76tUwZ70KOPxH0aRZKQOzkHG9Nhxnxu8rtRrDruc2
    permissions:
      - create_book
      - decrease_book_stock
      - update_book_stock
      - read_book
      - read_order
      - create_order